/**
 * dashboard-renderer.service.ts
 */
import type {
  DashboardConfiguration,
  DashboardRequestConfiguration,
  DashboardTemplateId,
  DashboardMetadata,
} from "@/types";

import { dashboardByTemplate } from "@/data/mock-dashboards";
import { buildAllWidgets } from "@/services/widget-factory.service";
import { generateDashboardLayout } from "@/services/layout-generator.service";

// ─────────────────────────────────────────────────────────────────────────────
// Routing logic
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Return true when the configuration contains enough data to drive
 * a fully dynamic render, bypassing the legacy template system.
 */
function hasDynamicContent(
  config: DashboardRequestConfiguration
): boolean {
  // Explicit widget declarations
  if ((config.widgets?.length ?? 0) > 0) return true;

  // Non-empty metrics map
  if (
    config.metrics &&
    Object.values(config.metrics).some(
      (v) => v !== undefined && v !== null
    )
  )
    return true;

  // Any analysis entry
  if (
    config.analysis &&
    Object.values(config.analysis).some((v) => v !== undefined)
  )
    return true;

  // Structured event items
  if ((config.events?.items?.length ?? 0) > 0) return true;

  return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function inferTheme(
  template: string
): "executive" | "sales" | "support" | "dark" {
  if (template.includes("sales")) return "sales";
  if (template.includes("support")) return "support";
  return "executive";
}

function inferSalesforceFlow(
  template: string
): DashboardMetadata["salesforceFlow"] {
  if (template.includes("sales")) return "GenerateSalesDashboardFlow";
  if (template.includes("support")) return "GenerateSupportDashboardFlow";
  if (template.includes("combined"))
    return "GenerateCombinedBusinessDashboardFlow";
  return "GenerateExecutiveDashboardFlow";
}

/**
 * Produce a stable dashboard ID from the Salesforce request ID (when available)
 * so that user-customised layouts persist across page refreshes.
 */
function buildDashboardId(requestId: string | undefined): string {
  return requestId ? `dynamic-${requestId}` : `dynamic-${Date.now().toString(36)}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Dynamic render path
// ─────────────────────────────────────────────────────────────────────────────

function buildDynamicDashboard(
  config: DashboardRequestConfiguration,
  requestId: string | undefined
): DashboardConfiguration {
  const widgets = buildAllWidgets(config);
  const layouts = generateDashboardLayout(widgets);

  const agentName =
    config.agentMetadata?.generatedBy ?? "Dashboard Visualization Agent";
  const description = config.agentMetadata
    ? `Generated by ${agentName} v${config.agentMetadata.version}`
    : "Generated by Salesforce Agentforce";

  return {
    id: buildDashboardId(requestId),
    title: config.dashboardName,
    description,
    template: (config.template as DashboardTemplateId) ?? "executive_combined",
    theme: inferTheme(config.template),
    layouts,
    widgets,
    metadata: {
      requestPrompt: config.dashboardName,
      salesforceFlow: inferSalesforceFlow(config.template),
      agentChain: ["Dashboard Visualization Agent"],
      generatedAt: config.generatedAt ?? new Date().toISOString(),
      source: "salesforce-agentforce-mock",
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Legacy render path (backward compatibility)
// ─────────────────────────────────────────────────────────────────────────────
function buildTemplateBasedDashboard(
  config: DashboardRequestConfiguration
): DashboardConfiguration {
  const template = config.template as DashboardTemplateId;
  // Graceful fallback: unknown template → executive_combined
  const base =
    dashboardByTemplate[template] ??
    dashboardByTemplate["executive_combined"];
  const dashboard = structuredClone(base);

  dashboard.title = config.dashboardName;
  dashboard.metadata.requestPrompt = config.dashboardName;

  dashboard.widgets.forEach((widget) => {
    if (widget.id === "kpi-1" && widget.type === "kpi") {
      widget.data.value =
        config.analysis?.revenue?.severity?.toUpperCase() ??
        widget.data.value;
    }

    if (widget.id === "kpi-2" && widget.type === "kpi") {
      widget.data.value = Number(
        config.metrics?.strategicOpportunities ?? 0
      );
    }

    if (widget.id === "kpi-3" && widget.type === "kpi") {
      widget.data.value = Number(config.metrics?.highPriorityCases ?? 0);
    }

    if (widget.id === "kpi-4" && widget.type === "kpi") {
      widget.data.value =
        config.analysis?.sla?.severity?.toUpperCase() ??
        widget.data.value;
    }

    if (widget.id === "insight-agentforce" && widget.type === "insight") {
      widget.data.bullets = [
        config.analysis?.revenue?.summary ??
          "No revenue analysis available",
        config.analysis?.sla?.summary ?? "No SLA analysis available",
        config.analysis?.executive?.summary ??
          "No executive insight available",
      ];
    }
  });

  return dashboard;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Convert a Dashboard_Request__c.Configuration__c payload into a
 * fully-resolved DashboardConfiguration ready for rendering.
 *
 * @param configuration  Parsed JSON from Configuration__c
 * @param requestId      Salesforce record Id or a stable string key;
 *                       used to build a deterministic dashboard id so that
 *                       user-saved layouts persist across sessions.
 */
export function renderDashboardFromConfiguration(
  configuration: DashboardRequestConfiguration,
  requestId?: string
): DashboardConfiguration {
  if (hasDynamicContent(configuration)) {
    return buildDynamicDashboard(configuration, requestId);
  }

  return buildTemplateBasedDashboard(configuration);
}
